In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
dataset = pd.read_csv('/content/Vaccine (1).csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [17]:
print(X_train)

[[17334     1     0 ...     2     1     0]
 [  563     0     1 ...     1     2     0]
 [15954     1     1 ...     2     1     2]
 ...
 [19527     1     2 ...     4     1     0]
 [21371     1     1 ...     1     2     0]
 [ 5437     2     1 ...     2     1     2]]


In [18]:
print(y_train)

[1 0 0 ... 0 1 0]


In [19]:
print(X_test)

[[ 1279     3     2 ...     4     1     0]
 [19727     1     1 ...     1     0     0]
 [16260     2     1 ...     1     1     1]
 ...
 [19555     2     1 ...     2     1     0]
 [22067     1     1 ...     2     1     0]
 [ 7618     0     1 ...     5     0     0]]


In [20]:
print(y_test)

[1 0 0 ... 0 0 0]


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
print(X_train)

[[ 0.51963498 -0.59574676 -2.07003584 ... -0.06528644  0.11848525
  -0.55642886]
 [-1.64713276 -1.72197277 -0.42720947 ... -0.82451306  1.40756917
  -0.55642886]
 [ 0.34134272 -0.59574676 -0.42720947 ... -0.06528644  0.11848525
   1.65162909]
 ...
 [ 0.80296464 -0.59574676  1.21561691 ...  1.4531668   0.11848525
  -0.55642886]
 [ 1.04120444 -0.59574676 -0.42720947 ... -0.82451306  1.40756917
  -0.55642886]
 [-1.01742517  0.53047925 -0.42720947 ... -0.06528644  0.11848525
   1.65162909]]


In [23]:
print(X_test)

[[-1.55462751  1.65670526  1.21561691 ...  1.4531668   0.11848525
  -0.55642886]
 [ 0.8288041  -0.59574676 -0.42720947 ... -0.82451306 -1.17059867
  -0.55642886]
 [ 0.38087709  0.53047925 -0.42720947 ... -0.82451306  0.11848525
   0.54760012]
 ...
 [ 0.80658216  0.53047925 -0.42720947 ... -0.06528644  0.11848525
  -0.55642886]
 [ 1.13112575 -0.59574676 -0.42720947 ... -0.06528644  0.11848525
  -0.55642886]
 [-0.73564589 -1.72197277 -0.42720947 ...  2.21239342 -1.17059867
  -0.55642886]]


In [24]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2176  203]
 [ 485  513]]


0.7962688777021024